### return all posts
GET http://localhost:8000/posts

### return a specific post
GET http://localhost:8000/posts/69a0d6f23ccad04e9cab7400

### get comments by post id
GET http://localhost:8000/posts/69aa7fe0350aa69c6278f9ec/comments

### return all users
GET http://localhost:8000/users

### return user by id
GET http://localhost:8000/users/69a0d23b1deec5dd4f138f84

### create a new user
POST http://localhost:8000/users
Content-Type: application/json

{
    "username": "Clare",
    "email": "clare@mail.com"
}

### create a wrong user
POST http://localhost:8000/users
Content-Type: application/json

{
    "userName": "Clare"
}

###
GET http://35.88.52.84:3000/posts

### register a new user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "Bob",
    "email": "bob@mail.com",
    "password": "password"
}


### login as a user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "bob@mail.com",
    "password": "password"
}

### login as another user
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "alice@mail.com",
    "password": "password"
}

### login as a user with wrong password
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "alice@mail.com",
    "password": "password"
}

### register an esisted user
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "username": "Alice",
    "email": "alice@mail.com",
    "password": "password"
}


### create a new post with a token
POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWNhZDc5ZDlkOTY5ZTE1OTc4N2EwODUiLCJpYXQiOjE3NzQ5MDExNzYsImV4cCI6MTc3NTUwNTk3Nn0.9balbq0sU0hYVdz_w_Hb4hioC1_AyrwliOuwrpRY_1c

{
    "title": "Travel low-carbon",
    "content": "Avoid taking plane"
}

### create a new post without a token
POST http://localhost:8000/posts
Content-Type: application/json

{
    "title": "Reuse Bags",
    "content": "Remember to bring your own bag"
}

### update a post
PUT http://localhost:8000/posts/69aa7fe0350aa69c6278f9ec
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWE5MjFiNGUxNjcyODQzOGUyMTY3MTQiLCJpYXQiOjE3NzI3ODEyNTgsImV4cCI6MTc3MzM4NjA1OH0.K_sCDkl-1_OLYPsymtJlRjXspDmo0Y_XIW1dxI8gQ-Y

{
    "title": "Reuse Bags updated",
    "content": "Remember to bring your own bag"
}

### delete a post with another user token
DELETE http://localhost:8000/posts/69cad8019d969e159787a089
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFhN2Q1ZWZiOTdmMGRiOTE2ZTcxZDgiLCJpYXQiOjE3NzQ5MDEzMzIsImV4cCI6MTc3NTUwNjEzMn0.Z9Wkri9Xhv_xDAoIea333USlltL4PDevEyWgpIn8ef0

### post a comment
POST http://localhost:8000/posts/69aa7fe0350aa69c6278f9ec/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFhN2Q1ZWZiOTdmMGRiOTE2ZTcxZDgiLCJpYXQiOjE3NzI3ODE3NDIsImV4cCI6MTc3MzM4NjU0Mn0.fI7zlTZyI5TRn24jhEGEul1N5mRwmEaI3txJtS2QbFI

{
    "content": "I don't think so."
}

### delete a comment
DELETE http://localhost:8000/posts/69aa7fe0350aa69c6278f9ec/comments/69aa818d1a46cc3773058141
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWFhN2Q1ZWZiOTdmMGRiOTE2ZTcxZDgiLCJpYXQiOjE3NzI3ODE3NDIsImV4cCI6MTc3MzM4NjU0Mn0.fI7zlTZyI5TRn24jhEGEul1N5mRwmEaI3txJtS2QbFI

### check loading balancer
GET http://climate-hub-alb-2135184959.us-west-2.elb.amazonaws.com/health